<?php

use Illuminate\Database\Seeder;

class AdminVideosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_videos')->delete();
        
        \DB::table('admin_videos')->insert(array (
            0 => 
            array (
                'id' => 4,
                'unique_id' => 'batman-begins5ced4248b6751',
                'title' => 'Batman Begins',
                'description' => 'Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.',
                'age' => '16',
                'details' => 'Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.',
                'category_id' => 4,
                'sub_category_id' => 28,
                'genre_id' => 28,
                'video' => 'http://localhost/uploads/videos/original/SV-2019-05-28-14-14-32-0134437eaf7b512f1204decb9a31ae98f27a9b4c.mp4',
                'video_subtitle' => 'http://localhost/uploads/subtitles/SV-2019-05-28-14-14-41-6f60ccead7ab56104e3b41a620e47491b1dc50f2.srt',
                'trailer_video' => 'https://www.youtube.com/embed/bkU7Cl2SSvI',
                'trailer_subtitle' => '',
                'default_image' => 'http://image.tmdb.org/t/p/w300/dr6x4GyyegBWtinPBzipY02J2lV.jpg',
                'video_gif_image' => '',
                'video_image_mobile' => '',
                'banner_image' => '',
                'ratings' => '4',
                'reviews' => '4',
                'status' => '1',
                'is_approved' => 1,
                'is_home_slider' => 0,
                'is_banner' => 0,
                'uploaded_by' => '2',
                'publish_time' => '2019-05-28 14:14:32',
                'duration' => '02:20:32',
                'trailer_duration' => '00:00:00',
                'video_resolutions' => NULL,
                'trailer_video_resolutions' => NULL,
                'compress_status' => 0,
                'main_video_compress_status' => 0,
                'trailer_compress_status' => 0,
                'video_resize_path' => NULL,
                'trailer_resize_path' => NULL,
                'edited_by' => 'admin',
                'ppv_created_by' => '2',
                'watch_count' => 0,
                'is_pay_per_view' => 0,
                'type_of_user' => 0,
                'type_of_subscription' => 0,
                'amount' => 0.0,
                'redeem_amount' => 0.0,
                'admin_amount' => 0.0,
                'user_amount' => 0.0,
                'created_at' => '2019-05-28 14:14:41',
                'updated_at' => '2019-05-28 14:14:41',
                'video_type' => 1,
                'video_upload_type' => 2,
                'position' => 1,
                'tmdb_video_id' => 272,
            ),
            1 => 
            array (
                'id' => 5,
                'unique_id' => 'wwe-royal-rumble-20155ced5c8e987a3',
                'title' => 'WWE Royal Rumble 2015',
                'description' => 'As is tradition at this yearly event, the card will be highlighted by the 30-man Royal Rumble match, where this year\'s winner will receive a WWE World Heavyweight Championship match at WrestleMania 31.',
                'age' => '16',
                'details' => 'As is tradition at this yearly event, the card will be highlighted by the 30-man Royal Rumble match, where this year\'s winner will receive a WWE World Heavyweight Championship match at WrestleMania 31.',
                'category_id' => 4,
                'sub_category_id' => 28,
                'genre_id' => 28,
                'video' => 'http://localhost/uploads/videos/original/SV-2019-05-28-16-06-38-ec167f04552972130c4475c58ef0b8230ec9d189.mp4',
                'video_subtitle' => 'http://localhost/uploads/subtitles/SV-2019-05-28-16-06-40-a34e034b48d56954220de88bf47c4c2bd1386ff4.srt',
                'trailer_video' => 'https://www.youtube.com/embed/MBBNp3BBLXM',
                'trailer_subtitle' => '',
                'default_image' => 'http://image.tmdb.org/t/p/w300/b1tS7A9625LZxstXTUBoUKnk3QF.jpg',
                'video_gif_image' => '',
                'video_image_mobile' => '',
                'banner_image' => '',
                'ratings' => '3',
                'reviews' => '3',
                'status' => '1',
                'is_approved' => 1,
                'is_home_slider' => 0,
                'is_banner' => 0,
                'uploaded_by' => '2',
                'publish_time' => '2019-05-28 16:06:38',
                'duration' => '02:43:38',
                'trailer_duration' => '00:00:00',
                'video_resolutions' => NULL,
                'trailer_video_resolutions' => NULL,
                'compress_status' => 0,
                'main_video_compress_status' => 0,
                'trailer_compress_status' => 0,
                'video_resize_path' => NULL,
                'trailer_resize_path' => NULL,
                'edited_by' => 'admin',
                'ppv_created_by' => '2',
                'watch_count' => 0,
                'is_pay_per_view' => 0,
                'type_of_user' => 0,
                'type_of_subscription' => 0,
                'amount' => 0.0,
                'redeem_amount' => 0.0,
                'admin_amount' => 0.0,
                'user_amount' => 0.0,
                'created_at' => '2019-05-28 16:06:40',
                'updated_at' => '2019-05-28 16:06:40',
                'video_type' => 1,
                'video_upload_type' => 2,
                'position' => 1,
                'tmdb_video_id' => 312159,
            ),
            2 => 
            array (
                'id' => 6,
                'unique_id' => 'the-magnificent-seven5ced60508b151',
                'title' => 'The Magnificent Seven',
                'description' => 'Looking to mine for gold, greedy industrialist Bartholomew Bogue seizes control of the Old West town of Rose Creek. With their lives in jeopardy, Emma Cullen and other desperate residents turn to bounty hunter Sam Chisolm for help. Chisolm recruits an eclectic group of gunslingers to take on Bogue and his ruthless henchmen. With a deadly showdown on the horizon, the seven mercenaries soon find themselves fighting for more than just money once the bullets start to fly.',
                'age' => '16',
                'details' => 'Looking to mine for gold, greedy industrialist Bartholomew Bogue seizes control of the Old West town of Rose Creek. With their lives in jeopardy, Emma Cullen and other desperate residents turn to bounty hunter Sam Chisolm for help. Chisolm recruits an eclectic group of gunslingers to take on Bogue and his ruthless henchmen. With a deadly showdown on the horizon, the seven mercenaries soon find themselves fighting for more than just money once the bullets start to fly.',
                'category_id' => 4,
                'sub_category_id' => 12,
                'genre_id' => 12,
                'video' => 'http://localhost/uploads/videos/original/SV-2019-05-28-16-22-40-2afac80c35982b947c211071eda5e7f424db95a8.mp4',
                'video_subtitle' => 'http://localhost/uploads/subtitles/SV-2019-05-28-16-22-41-576f02a8f0dcac78fe877e0a607c7de46ba7e6ad.srt',
                'trailer_video' => 'https://www.youtube.com/embed/q-RBA0xoaWU',
                'trailer_subtitle' => '',
                'default_image' => 'http://image.tmdb.org/t/p/w300/cparcxTFuHdlSOP3MJOpN7Ec9NB.jpg',
                'video_gif_image' => '',
                'video_image_mobile' => '',
                'banner_image' => '',
                'ratings' => '3',
                'reviews' => '3',
                'status' => '1',
                'is_approved' => 1,
                'is_home_slider' => 0,
                'is_banner' => 0,
                'uploaded_by' => '2',
                'publish_time' => '2019-05-28 16:22:40',
                'duration' => '02:12:40',
                'trailer_duration' => '00:00:00',
                'video_resolutions' => NULL,
                'trailer_video_resolutions' => NULL,
                'compress_status' => 0,
                'main_video_compress_status' => 0,
                'trailer_compress_status' => 0,
                'video_resize_path' => NULL,
                'trailer_resize_path' => NULL,
                'edited_by' => 'admin',
                'ppv_created_by' => '2',
                'watch_count' => 0,
                'is_pay_per_view' => 0,
                'type_of_user' => 0,
                'type_of_subscription' => 0,
                'amount' => 0.0,
                'redeem_amount' => 0.0,
                'admin_amount' => 0.0,
                'user_amount' => 0.0,
                'created_at' => '2019-05-28 16:22:41',
                'updated_at' => '2019-05-28 16:22:41',
                'video_type' => 1,
                'video_upload_type' => 2,
                'position' => 1,
                'tmdb_video_id' => 333484,
            ),
        ));
        
        
    }
}
