<?php

use Illuminate\Database\Seeder;

class AdminVideosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_videos')->delete();
        
        \DB::table('admin_videos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'unique_id' => '5ced3865d150b5ced3865d1a1a',
                'title' => 'Suscipit voluptas aspernatur vel sit.',
                'description' => 'Repellendus cumque quo et error praesentium et non.',
                'age' => '33',
                'details' => 'Expedita et est et est cumque.',
                'category_id' => 1,
                'sub_category_id' => 1,
                'genre_id' => 0,
                'video' => 'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_30mb.mp4',
                'video_subtitle' => '',
                'trailer_video' => 'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_5mb.mp4',
                'trailer_subtitle' => '',
                'default_image' => 'https://sample-videos.com/img/Sample-jpg-image-200kb.jpg',
                'video_gif_image' => '',
                'video_image_mobile' => '',
                'banner_image' => 'https://sample-videos.com/img/Sample-jpg-image-200kb.jpg',
                'ratings' => '4',
                'reviews' => 'Aut reprehenderit qui reprehenderit.',
                'status' => '1',
                'is_approved' => 0,
                'is_home_slider' => 0,
                'is_banner' => 0,
                'uploaded_by' => '0',
                'publish_time' => '2019-05-28 00:00:00',
                'duration' => '11:10:50',
                'trailer_duration' => '17:33:02',
                'video_resolutions' => NULL,
                'trailer_video_resolutions' => NULL,
                'compress_status' => 0,
                'main_video_compress_status' => 0,
                'trailer_compress_status' => 0,
                'video_resize_path' => NULL,
                'trailer_resize_path' => NULL,
                'edited_by' => 'admin',
                'ppv_created_by' => '1',
                'watch_count' => 1,
                'is_pay_per_view' => 0,
                'type_of_user' => 0,
                'type_of_subscription' => 0,
                'amount' => 30.0,
                'redeem_amount' => 1.25,
                'admin_amount' => 2.25,
                'user_amount' => 3.25,
                'created_at' => '2019-05-28 13:32:21',
                'updated_at' => '2019-05-28 14:10:45',
                'video_type' => 1,
                'video_upload_type' => 1,
                'position' => 1,
                'tmdb_video_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'unique_id' => '5ced3865d21385ced3865d2481',
                'title' => 'Facere molestiae quia voluptatem.',
                'description' => 'Error consequatur itaque eligendi sit qui sint culpa rerum impedit.',
                'age' => '41',
                'details' => 'Rerum dignissimos iste ut corporis velit omnis totam omnis veniam dolores.',
                'category_id' => 1,
                'sub_category_id' => 1,
                'genre_id' => 0,
                'video' => 'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_30mb.mp4',
                'video_subtitle' => '',
                'trailer_video' => 'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_5mb.mp4',
                'trailer_subtitle' => '',
                'default_image' => 'https://sample-videos.com/img/Sample-jpg-image-200kb.jpg',
                'video_gif_image' => '',
                'video_image_mobile' => '',
                'banner_image' => 'https://sample-videos.com/img/Sample-jpg-image-200kb.jpg',
                'ratings' => '4',
                'reviews' => 'Non facilis eum aut veniam hic.',
                'status' => '0',
                'is_approved' => 0,
                'is_home_slider' => 0,
                'is_banner' => 0,
                'uploaded_by' => '0',
                'publish_time' => '2019-05-28 00:00:00',
                'duration' => '15:58:09',
                'trailer_duration' => '04:22:40',
                'video_resolutions' => NULL,
                'trailer_video_resolutions' => NULL,
                'compress_status' => 0,
                'main_video_compress_status' => 0,
                'trailer_compress_status' => 0,
                'video_resize_path' => NULL,
                'trailer_resize_path' => NULL,
                'edited_by' => 'admin',
                'ppv_created_by' => '1',
                'watch_count' => 3,
                'is_pay_per_view' => 0,
                'type_of_user' => 0,
                'type_of_subscription' => 0,
                'amount' => 38.0,
                'redeem_amount' => 1.25,
                'admin_amount' => 2.25,
                'user_amount' => 3.25,
                'created_at' => '2019-05-28 13:32:21',
                'updated_at' => '2019-05-28 13:32:21',
                'video_type' => 1,
                'video_upload_type' => 1,
                'position' => 1,
                'tmdb_video_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'unique_id' => '5ced3865d28ea5ced3865d2c22',
                'title' => 'Sit soluta enim aut.',
                'description' => 'Consequatur ipsum velit inventore expedita beatae explicabo reprehenderit odit voluptatibus sapiente delectus.',
                'age' => '27',
                'details' => 'Eius sunt facilis laborum sit minus non error laboriosam fuga.',
                'category_id' => 1,
                'sub_category_id' => 1,
                'genre_id' => 0,
                'video' => 'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_30mb.mp4',
                'video_subtitle' => '',
                'trailer_video' => 'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_5mb.mp4',
                'trailer_subtitle' => '',
                'default_image' => 'https://sample-videos.com/img/Sample-jpg-image-200kb.jpg',
                'video_gif_image' => '',
                'video_image_mobile' => '',
                'banner_image' => 'https://sample-videos.com/img/Sample-jpg-image-200kb.jpg',
                'ratings' => '3',
                'reviews' => 'Autem et vel cum.',
                'status' => '1',
                'is_approved' => 1,
                'is_home_slider' => 0,
                'is_banner' => 1,
                'uploaded_by' => '0',
                'publish_time' => '2019-05-28 00:00:00',
                'duration' => '15:12:56',
                'trailer_duration' => '12:18:23',
                'video_resolutions' => NULL,
                'trailer_video_resolutions' => NULL,
                'compress_status' => 0,
                'main_video_compress_status' => 0,
                'trailer_compress_status' => 0,
                'video_resize_path' => NULL,
                'trailer_resize_path' => NULL,
                'edited_by' => 'admin',
                'ppv_created_by' => '1',
                'watch_count' => 1,
                'is_pay_per_view' => 0,
                'type_of_user' => 0,
                'type_of_subscription' => 0,
                'amount' => 32.0,
                'redeem_amount' => 1.25,
                'admin_amount' => 2.25,
                'user_amount' => 3.25,
                'created_at' => '2019-05-28 13:32:21',
                'updated_at' => '2019-05-28 13:32:21',
                'video_type' => 1,
                'video_upload_type' => 1,
                'position' => 1,
                'tmdb_video_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'unique_id' => 'batman-begins5ced4248b6751',
                'title' => 'Batman Begins',
                'description' => 'Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.',
                'age' => '16',
                'details' => 'Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.',
                'category_id' => 4,
                'sub_category_id' => 28,
                'genre_id' => 28,
                'video' => 'http://localhost/uploads/videos/original/SV-2019-05-28-14-14-32-0134437eaf7b512f1204decb9a31ae98f27a9b4c.mp4',
                'video_subtitle' => 'http://localhost/uploads/subtitles/SV-2019-05-28-14-14-41-6f60ccead7ab56104e3b41a620e47491b1dc50f2.srt',
                'trailer_video' => 'https://www.youtube.com/watch?v=bkU7Cl2SSvI',
                'trailer_subtitle' => '',
                'default_image' => 'http://image.tmdb.org/t/p/w300/dr6x4GyyegBWtinPBzipY02J2lV.jpg',
                'video_gif_image' => '',
                'video_image_mobile' => '',
                'banner_image' => '',
                'ratings' => '4',
                'reviews' => '4',
                'status' => '1',
                'is_approved' => 1,
                'is_home_slider' => 0,
                'is_banner' => 0,
                'uploaded_by' => '2',
                'publish_time' => '2019-05-28 14:14:32',
                'duration' => '02:20:32',
                'trailer_duration' => '00:00:00',
                'video_resolutions' => NULL,
                'trailer_video_resolutions' => NULL,
                'compress_status' => 0,
                'main_video_compress_status' => 0,
                'trailer_compress_status' => 0,
                'video_resize_path' => NULL,
                'trailer_resize_path' => NULL,
                'edited_by' => 'admin',
                'ppv_created_by' => '2',
                'watch_count' => 0,
                'is_pay_per_view' => 0,
                'type_of_user' => 0,
                'type_of_subscription' => 0,
                'amount' => 0.0,
                'redeem_amount' => 0.0,
                'admin_amount' => 0.0,
                'user_amount' => 0.0,
                'created_at' => '2019-05-28 14:14:41',
                'updated_at' => '2019-05-28 14:14:41',
                'video_type' => 1,
                'video_upload_type' => 2,
                'position' => 1,
                'tmdb_video_id' => 272,
            ),
        ));
        
        
    }
}